pages:
  script:
    - mkdir -p public
    - cp index.html style.css public/
  artifacts:
    paths:
      - public
  publish: public
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'





